import os
import json
import json5
import random
from typing import List, Dict
import openai
from tqdm import tqdm
from dotenv import load_dotenv
from eval import evaluate_summary
import argparse
load_dotenv()
from groq import Groq
import re
import ast
import time
from collections import deque
import tiktoken
import statistics
import pandas as pd


# Record the time and token usage for each API call
token_window = deque()
TOKEN_LIMIT_PER_MIN = 14000000000

def wait_for_token_budget(tokens_needed):
    now = time.time()
    while token_window and now - token_window[0][0] > 60:
        token_window.popleft()

    current_token_usage = sum(t[1] for t in token_window)
    if current_token_usage + tokens_needed > TOKEN_LIMIT_PER_MIN:
        wait_time = 60 - (now - token_window[0][0])
        # print(f"⏳ Token limit reached, waiting {int(wait_time)+1}s...")
        time.sleep(wait_time + 7)  # wait for the remaining time plus 2 seconds buffer

def record_token_usage(tokens_used):
    token_window.append((time.time(), tokens_used))

def estimate_tokens(text, model="gpt-4o"):
    enc = tiktoken.encoding_for_model(model)
    return len(enc.encode(text))

# ========== Robust Parser Class ==========
def parse_captain_result(raw_text: str) -> dict:
    """Parse CaptainAgent output into JSON structure"""
    prompt = f"""
You are given the following text containing the description about a task and a list of aspects and their summaries. Please parse this content into a structured JSON format. The expected JSON format is:

{{
  "Aspect Title 1": "summary for aspect 1...",
  "Aspect Title 2": "summary for aspect 2...",
  ...
}}

Here is the text to parse:

\"\"\"
{raw_text}
\"\"\"

Only output the valid JSON. Do not include any explanation, note, or commentary.
""".strip()
    _, llm_client = _init_llm_client("gpt-4o-mini")
    response, tokens = _chat_completion(prompt, temperature=0.7, model="gpt-4o-mini", llm_client=llm_client)

    try:
        summaries = ast.literal_eval(response.replace("```json", "").replace("```", "").strip())
        return summaries, tokens
    except:
        print("❌ Failed to parse JSON response from model.")
        print("Raw response:\n", response)
        return {}, 0


def final_answer_from_multiple_responses(responses: List[Dict[str, str]], article: str, aspects: List[str], model: str, gemini_api_key: str = None, predicted_aspect: int = 0, is_provide_aspect_num: bool = False) -> Dict[str, str]:
    ensemble_input = {
        "multilple agents' responses": responses,
        "article": article,
    }

    predicted_aspect_num = predicted_aspect
    count_hint = f"- According to other agents, this article likely contains around **{predicted_aspect_num}** aspects. Please take this into account when generating your own aspect summaries." if predicted_aspect_num > 0 else ""

    prompt = f"""
You are given multiple structured outputs generated by different agents who analyzed a financial article based on specific aspects.
Your task is to merge and finalize the aspect-based summaries. Ensure:
- Include only aspects that are clearly supported by the article.
- Merge or generalize similar or overly specific aspects into broader, meaningful themes.
- Choose the consistent most summary per aspect, or synthesize a better one if needed.
{count_hint}

Input:
{json.dumps(ensemble_input, indent=2)}

Return only the final result in this format:
{{
  "Aspect Title 1": "summary...",
  "Aspect Title 2": "summary...",
  ...
}}
""".strip()
    
    # print(f"Final prompt for {model}:\n{prompt}\n")

    _, llm_client = _init_llm_client(model, gemini_api_key=gemini_api_key)
    response, tokens = _chat_completion(prompt, model=model, temperature=0.1, llm_client=llm_client)

    try:
        match = re.search(r"\{.*?\}", response, re.DOTALL)
        # summaries = response.replace("```json", "").replace("```", "").strip()
        parsed = ast.literal_eval(match.group(0))
        tokens2 = 0

        return parsed, tokens + tokens2
    except: 
        parsed, tokens2 = parse_captain_result(response)
    
        return parsed, tokens + tokens2

def predict_num_aspects(article: str, model: str = "gpt-4o", gemini_api_key: str = None) -> int:
    prompt = f"""
You are given a financial article. Estimate how many distinct, non-overlapping aspects or key themes are discussed in the article. Only return a single integer representing the number of aspects.

Article:
{article}
"""
    _, llm_client = _init_llm_client(model, gemini_api_key=gemini_api_key)
    response, tokens = _chat_completion(prompt, model=model, temperature=0.7, llm_client=llm_client)

    match = re.search(r"\d+", response)

    # print(f"Response from {model}:\n{response}\n")

    return int(match.group(0)), tokens   # default fallback


# ========== Phase 1: Suggest and Summarize Aspects ==========

def generate_revised_aspects_and_summary(
    article: str,
    given_aspects: List[str],
    model: str = "gpt-4o-mini",
    cot_mode: str = "direct",
    num_samples: int = 5,
    gemini_api_key: str = None,
    ground_truth_aspects_num: int = 0,
    y: int = 0,
    n: int = 0,
    is_provide_aspect_num: bool = False,
    predicted_aspect: int = 0
) -> Dict[str, str]:
    """
    Use LLM to revise the given aspects based on article content and produce an aspect-based summary.

    If cot=True, use Chain of Thought prompt and extract summary only from the returned structured reasoning.
    """
    aspects_str = "\n".join([f"{i+1}. {a}" for i, a in enumerate(given_aspects)])

    
    def build_prompt(article: str, aspects_str: str, style: str) -> str:
        count_hint = ""
        predicted_aspect_num = 0
        tokens_predict = 0

        if is_provide_aspect_num and predicted_aspect == 0:
            predicted_aspect_num, tokens_predict = predict_num_aspects(article, model=model, gemini_api_key=gemini_api_key)
            count_hint = f"- According to other agents, this article likely contains around **{predicted_aspect_num}** aspects. Please take this into account when generating your own aspect summaries." if predicted_aspect_num > 0 else ""
        elif is_provide_aspect_num and predicted_aspect != 0:
            predicted_aspect_num = predicted_aspect
            count_hint = f"- According to other agents, this article likely contains around **{predicted_aspect_num}** aspects. Please take this into account when generating your own aspect summaries." if predicted_aspect_num > 0 else ""

        if style == "cot":
            prompt = f"""
    You are a financial analyst assistant tasked with revising a list of section titles (called "aspects") based on the article content below. Use a chain-of-thought approach: think step-by-step to evaluate whether each aspect is relevant and what summary should accompany it.

    Instructions:
    1. Assign an **action** to the aspect:
    - **retain**: the aspect is relevant, well-phrased, and clearly supported by the article.
    - **modify**: the aspect is relevant but needs rephrasing or more specificity.
    - **delete**: the aspect is irrelevant, redundant, or unsupported by the article.
    - **add**: the aspect was not in the original list but is important present in the article.

    2. Provide a **brief reasoning** explaining why you chose that action.

    3. Write a **concise summary** that explains what the article says about this aspect. If the aspect is deleted, return "".

    Guidelines:
    - Be specific. Avoid vague or overly broad aspects.
    - Do not include deleted aspects in the final output.
    - Think step-by-step and justify your decisions.
    {count_hint}

    Only return the result as a JSON object where:
    Each key is a finalized aspect title, and the value is a dict with:
    - "action": "retain" | "modify" | "delete" | "add"
    - "reasoning": why it was kept/added
    - "summary": concise summary

    Format:
    {{
    "Aspect Title 1": {{
        "action": "retain",
        "reasoning": "Step-by-step reasoning...",
        "summary": "Final summary of this aspect..."
    }},
    "Aspect Title 2": {{
        "action": "add",
        "reasoning": "Step-by-step reasoning...",
        "summary": "Final summary of this aspect..."
    }},
    ...
    }}

    Article:
    {article}

    Provided Aspects:
    {aspects_str}
    """.strip()
            
        elif style == "direct":
            prompt = f"""
    You are given a financial article and an initial list of section titles (called "aspects"). Your task is to revise this list to better reflect the key themes and content of the article.

    Instructions:

    1. For each aspect in the **provided list**, perform the following:
    - Label it as:
        - **Retain** if it is well-phrased, specific, and clearly supported by the article.
        - **Modify** if it is relevant but needs rephrasing or more specific focus.
        - **Delete** if it is irrelevant, redundant, or unsupported by the article.

    2. Identify any **new aspects** that are important but missing from the provided list:
    - Clearly name the new aspect.
    - Summarize what the article says about it.

    3. For each finalized aspect (retained, modified, or newly added), write a **concise summary** explaining what the article says about that topic.

    Guidelines:
    - Ensure aspects are **clear, specific, and non-overlapping**.
    - **Do not include deleted aspects** in the final output.
    - Your summaries should be **factual and grounded in the article**.
    - {count_hint}

    Only return your result in the following JSON format:
    {{
    "Aspect Title 1": "summary for aspect 1...",
    "Aspect Title 2": "summary for aspect 2...",
    ...
    }}

    Article:
    {article}

    Provided Aspects:
    {aspects_str}
    """.strip()
            
        return prompt, predicted_aspect_num, tokens_predict
    
    if cot_mode == "cot_sc":
        all_responses = []
        temp_tokens = 0
        total_aspects_nums = []

        for _ in range(num_samples):
            prompt, predicted_aspect_num, token_predict = build_prompt(article, aspects_str, style="cot")
            # print(f"Prompt for {model}:\n{prompt}\n")
            # print(1/0)

            total_aspects_nums.append(predicted_aspect_num)

            _, llm_client = _init_llm_client(model, gemini_api_key=gemini_api_key)
            response, tokens1 = _chat_completion(prompt, model=model, temperature=0.7, llm_client=llm_client)

            try:
                match = re.search(r"\{.*?\}", response, re.DOTALL)
                summaries = ast.literal_eval(match.group(0))
                parsed = summaries
                tokens2 = 0
            except:
                parsed, tokens2 = parse_captain_result(response)

            # time.sleep(45)
            # print(f"Response from {model}:\n{response}\n")
            # print(1/0)

            if parsed:
                all_responses.append(parsed)

            temp_tokens += tokens1 + tokens2 + token_predict

        if not all_responses:
            return {}, 0

        final, tokens3 = final_answer_from_multiple_responses(all_responses, article, given_aspects, model, gemini_api_key=gemini_api_key, predicted_aspect=predicted_aspect_num)


        return final, temp_tokens + tokens3, statistics.median(total_aspects_nums) if total_aspects_nums else 0

    else:
        prompt, predicted_aspect_num, token_predict = build_prompt(article, aspects_str, style=cot_mode)
        # print(f"Prompt for {model}:\n{prompt}\n")

        _, llm_client = _init_llm_client(model, gemini_api_key=gemini_api_key)
        response, tokens1 = _chat_completion(prompt, model=model, temperature=0.7, llm_client=llm_client)

        # print(f"Response from {model}:\n{response}\n")
        try:
            match = re.search(r"\{.*?\}", response, re.DOTALL)
            summaries = ast.literal_eval(match.group(0))

            parsed = summaries
            tokens2 = 0
        except:
            parsed, tokens2 = parse_captain_result(response)
        # print(f"Parsed result: {parsed}\n")

        if cot_mode == "cot":
            # If using Chain of Thought, we need to extract the final summary from the structured reasoning
            final_summary = {}
            for aspect, details in parsed.items():
                if isinstance(details, dict) and "action" in details and "summary" in details:
                    if details["action"] != "delete" and details["summary"]:
                        final_summary[aspect] = details["summary"]

                elif isinstance(details, dict) and "summary" in details and details["summary"]:
                    final_summary[aspect] = details["summary"]
                elif isinstance(details, str):
                    final_summary[aspect] = details    
            parsed = final_summary

        return parsed, tokens1 + tokens2 + token_predict, predicted_aspect_num 
    


# ========== Utility: OpenAI API Call ==========

def _init_llm_client(model_name: str, gemini_api_key: str = None):
    """
    Initialize either OpenAI or Groq client based on model name.
    """
    if model_name.startswith("gpt") or model_name.startswith("o3"):
        api_key = os.getenv("OPENAI_API_KEY")
        return "openai", openai.OpenAI(api_key=api_key)
    
    elif "llama" in model_name.lower() or "deepseek" in model_name.lower():
        # api_key = os.getenv("GROQ_API_KEY2")
        api_key = os.getenv("DeepInfra_API_KEY")
        return "deep_infra", openai.OpenAI(api_key=api_key, base_url="https://api.deepinfra.com/v1/openai")
    
    elif 'gemini' or "gemma" in model_name:
        api_key = os.getenv(gemini_api_key)
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
        )

        return "gemini", client
    else:
        raise ValueError(f"Unsupported model: {model_name}")


# Helper for OpenAI chat completion
def _chat_completion(prompt: str, model: str, temperature: float, llm_client) -> str:
    try:
        estimate_prompt_tokens = estimate_tokens(prompt, model="gpt-4o")
        estimated_tokens = estimate_prompt_tokens + 1500  # prompt word count + buffer
        wait_for_token_budget(estimated_tokens)

        if 'o3' in model:
            response = llm_client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
            )
        else:
            response = llm_client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                temperature=temperature,
                # max_tokens=16348,
            )
        # print(f"{response.choices[0].message.content.strip()}")
        actual_tokens = response.usage.total_tokens
        record_token_usage(actual_tokens)

        return response.choices[0].message.content.strip(), actual_tokens
    except Exception as e:
        print(f"⚠️ API call failed: {e}")
        return "", ""

def list_all_json_files(root_dir):
    json_files = []
    for dirpath, dirnames, filenames in os.walk(root_dir):
        for file in filenames:
            if file.endswith('.json'):
                full_path = os.path.join(dirpath, file)
                json_files.append(full_path)
    return json_files

# ========== Main Workflow ==========

def main(
        folder_path: str, 
        all_aspects: List[str], 
        output_path: str, 
        cot_mode: str = "direct",
        model: str = "gpt-4o-mini", 
        y: int = 2, 
        n: int = 2, 
        gemini_api_key: str = None,
        is_provide_aspect_num: bool = False,
        aspect_predictions_map: Dict[str, int] = None,
        cuda: int = 0):
    """
    Process each article: revise aspects using LLM, summarize per aspect, and save results.

    If cot=True, use Chain-of-Thought prompt style.
    """

    temp = 0
    for file_path in tqdm(folder_path):
        # temp += 1
        if is_provide_aspect_num and aspect_predictions_map:
            predicted_aspect = aspect_predictions_map[file_path]
        else:
            predicted_aspect = 0
        filename = os.path.basename(file_path)

        if not filename.endswith('.json'):
            continue

        number_aspect = file_path.split('/')[-2]
        output_file = os.path.join(output_path, f"{number_aspect}_{filename}")
    
        if os.path.exists(output_file):
            continue

        # with open(f"../../Synthetic_data/{file_path}", 'r', encoding='utf-8') as f:
        # print(f"Processing file: {file_path}")  
        with open(f"{file_path}", 'r', encoding='utf-8') as f:
            data = json.load(f)

        article = data.get('document', '').strip()
        ground_truth_aspects = data.get('aspects', [])
        ground_truth_summaries = data.get('aspect_summary', {})

        # Sample 2 ground truth aspects and 2 unrelated ones
        provided_aspects = []
        # == true data ==
        if y > 0:
            true_aspects = random.sample(ground_truth_aspects, k=min(y, len(ground_truth_aspects)))
            provided_aspects.extend(true_aspects)    
        # == fake data ==
        if n > 0:
            candidate_aspects = list(set(all_aspects) - set(ground_truth_aspects))        
            random_aspects = random.sample(candidate_aspects, k=n)
            provided_aspects.extend(random_aspects)

        # Generate revised aspects and summaries
        revised, tokens, predicted_aspect_num = generate_revised_aspects_and_summary(
            article, provided_aspects, model=model, cot_mode=cot_mode, num_samples=3, 
            gemini_api_key=gemini_api_key, y=y, n=n, is_provide_aspect_num=is_provide_aspect_num, predicted_aspect=predicted_aspect)

        if revised:
            evaluation_result = evaluate_summary(list(ground_truth_summaries.values()), list(revised.values()), cuda=cuda)
            result = {
                "document": article,
                "ground_truth_aspects": ground_truth_aspects,
                "ground_truth_aspect_summary": ground_truth_summaries,
                "provided_aspects": provided_aspects,
                "generated_revised_aspects_summary": revised,
                "pairing": evaluation_result["pairing"],
                "metrics": evaluation_result["metrics"],
                "total_tokens": tokens,
                "predicted_aspect_num": predicted_aspect_num,
            }

            # Save output per article
            with open(output_file, "w", encoding="utf-8") as f:
                json.dump(result, f, ensure_ascii=False, indent=2)

def load_prediction_csv(path="test_results.csv"):
    df = pd.read_csv(path)
    return dict(zip(df['file_name'], df['prediction']))

# ========== Entry Point ==========

if __name__ == "__main__":
    from report_template import report_template_dict

    all_aspects = []
    for key, value in report_template_dict.items():
        if isinstance(value, list):
            all_aspects.extend(value)
        else:
            all_aspects.append(value)

    model = "gpt-4o"
    # model = 'llama3-8b-8192'

    parser = argparse.ArgumentParser(description="Run aspect summarization with optional Chain of Thought reasoning.")
    parser.add_argument("--cot_mode", type=str, choices=["direct", "cot", "cot_sc"], default="direct",
                        help="Prompting mode: direct / cot / cot_sc")
    parser.add_argument("--model", type=str, default=model, help="Model to use for summarization (default: gpt-4o)")
    parser.add_argument("--y", type=int, default=2, help="Number of true aspects to sample from ground truth")
    parser.add_argument("--n", type=int, default=2, help="Number of unrelated aspects to add")
    parser.add_argument("--gemini_api_key", type=str, default="GEMINI_API_KEY_BRYANT", help="Environment variable for Gemini API key")
    parser.add_argument("--provide_aspect_num", action="store_true", help="Predict number of aspects from article")
    parser.add_argument("--aspect_source", type=str, choices=["predict", "csv"], default="predict",
                    help="Source for predicted aspect number: 'predict' or 'csv'")
    parser.add_argument("--cuda", type=int, default=0, help="CUDA device index for BERTScore calculation")

    args = parser.parse_args()

    if 'gemma' in args.model.lower() or 'gemini' in args.model.lower():
        TOKEN_LIMIT_PER_MIN = 245000 # 14500

    train_files = list_all_json_files("../../Synthetic_data/gemini_filtered_data/")

    # print(len(train_files))

    if args.provide_aspect_num:
        output_folder = f"../../Result/{args.cot_mode}_prompt{"_with_predicted_aspect" if args.aspect_source == "predict" else "_with_csv_aspect"}/gemini_filtered_data_y{args.y}n{args.n}/{args.model}/"
    else:
        output_folder = f"../../Result/{args.cot_mode}_prompt/gemini_filtered_data_y{args.y}n{args.n}/{args.model}/"
    os.makedirs(output_folder, exist_ok=True)

    # Run with Chain-of-Thought enabled
    if args.aspect_source == "csv":
        # Load aspect predictions from CSV
        aspect_predictions_map = load_prediction_csv("test_results.csv")
    else:
        # Predict aspect numbers from articles
        aspect_predictions_map = {}

    main(train_files, all_aspects, output_folder, cot_mode=args.cot_mode, model=args.model, y=args.y, n=args.n, gemini_api_key=args.gemini_api_key, is_provide_aspect_num=args.provide_aspect_num, aspect_predictions_map=aspect_predictions_map, cuda=args.cuda)